spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost/cronosadmindb
spring.datasource.username=postgres
spring.datasource.password=baggio0103

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
